language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  #- "3.7-dev"  # 3.7 development branch

addons:
  postgresql: "9.5"
services:
  - postgresql
# command to install dependencies
install:
  - 'pip install pipenv'
  - 'pipenv sync --dev'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# to start the test
script:
  - pytest --cov=amz_review_scraper
  - black --check --verbose .
branches:
  only:
  - gh-pages
  - /.*/
after_success:
  - coveralls
