language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - 'pip install pipenv'
  - 'pipenv sync'
# to start the test
script:
  - python -m pytest
  - pytest --cov=amz_review_scraper
  - black --check --verbose
branches:
  only:
  - gh-pages
  - /.*/
after_success:
  - coveralls
